### ISSUE TITLE
[Proposal] Texture and Sprite API updates

### ISSUE THREAD

**Issue by Bombfuse** [mooman219/storm#6]
# Problem
Sprites require their size property to be set to the size of the texture in order to render 1:1 in regard to the texture.

It's impossible to set the Sprite's size to the texture size without knowing the size of the texture.

Currently there is no way to easily get the size of a texture.

# Proposals

1) Texture should have a new function `size()` which calculates the size of the Texture and returns it.

2) Sprite should have a function `from_texture(texture)` which will create the Sprite with the metadata of the texture in mind. This function will automatically set the size to the correct value.

3) `load_texture()` can also return the meta data of the texture when it's created.

```rust
// 1
let size = texture.size()

// 2
let sprite = Sprite::from_texture(engine.load_texture("path/to/texture.png", TextureFormat::PNG));

// 3
let (tex, tex_info) = engine.load_texture("path/to/texture.png", TextureFormat::PNG);

```

**Comment by mooman219** [comment]
Done
